# Generated by Django 5.2.7 on 2025-12-07 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_alter_item_stock_iteminterest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemInterest',
        ),
    ]
