# Generated by Django 5.2.7 on 2026-03-18 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_delete_iteminterest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='min_negotiable_price',
        ),
    ]
