# Generated by Django 5.2.7 on 2026-03-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_remove_item_min_negotiable_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='last_viewed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='item',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ItemAnalytics',
        ),
    ]
