openapi: 3.0.3
info:
  title: Clippr API
  version: 1.0.0
  description: An automated documantatio for the API's of Clippr
paths:
  /api/item/:
    get:
      operationId: item_list
      parameters:
      - name: amount
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      tags:
      - item
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedItemBasicList'
          description: ''
    post:
      operationId: item_create
      tags:
      - item
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Item'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Item'
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
          description: ''
  /api/item/{id}/:
    get:
      operationId: item_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this item.
        required: true
      tags:
      - item
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
          description: ''
    put:
      operationId: item_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this item.
        required: true
      tags:
      - item
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Item'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Item'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
          description: ''
    patch:
      operationId: item_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this item.
        required: true
      tags:
      - item
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedItem'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedItem'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedItem'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
          description: ''
    delete:
      operationId: item_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this item.
        required: true
      tags:
      - item
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /api/item/my-clippings/:
    get:
      operationId: item_my_clippings_retrieve
      tags:
      - item
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/item/my-clippings/create/:
    post:
      operationId: item_my_clippings_create_create
      tags:
      - item
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/review/account/{username}/:
    get:
      operationId: review_account_list
      parameters:
      - in: path
        name: username
        schema:
          type: string
        required: true
      tags:
      - review
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccountReview'
          description: ''
  /api/review/create/:
    post:
      operationId: review_create_create
      tags:
      - review
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/review/item/{item_id}/:
    get:
      operationId: review_item_list
      parameters:
      - in: path
        name: item_id
        schema:
          type: integer
        required: true
      tags:
      - review
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ItemReview'
          description: ''
  /api/user/{id}/socials/:
    get:
      operationId: user_socials_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user.
        required: true
      tags:
      - user
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
  /api/user/{id}/verify/:
    post:
      operationId: user_verify_create
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user.
        required: true
      tags:
      - user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
  /api/user/avatar/:
    get:
      operationId: user_avatar_retrieve
      tags:
      - user
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    post:
      operationId: user_avatar_create
      tags:
      - user
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    delete:
      operationId: user_avatar_destroy
      tags:
      - user
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /api/user/by_username/{name}/:
    get:
      operationId: user_by_username_retrieve
      parameters:
      - in: path
        name: name
        schema:
          type: string
        required: true
      tags:
      - user
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
  /api/user/delete/:
    post:
      operationId: user_delete_create
      tags:
      - user
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/user/list/:
    get:
      operationId: user_list_list
      tags:
      - user
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserBasic'
          description: ''
  /api/user/login/:
    post:
      operationId: user_login_create
      tags:
      - user
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/user/logout/:
    post:
      operationId: user_logout_create
      tags:
      - user
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/user/refresh/:
    get:
      operationId: user_refresh_retrieve
      tags:
      - user
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/user/register/:
    post:
      operationId: user_register_create
      tags:
      - user
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/user/unverified/:
    get:
      operationId: user_unverified_retrieve
      tags:
      - user
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
  /api/user/update_socials/:
    post:
      operationId: user_update_socials_create
      tags:
      - user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
components:
  schemas:
    AccountReview:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        rating:
          type: string
          format: decimal
          pattern: ^-?\d{0,1}(?:\.\d{0,1})?$
        comment:
          type: string
          nullable: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        seller:
          type: integer
      required:
      - created_at
      - id
      - rating
      - seller
    Image:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        image:
          type: string
          format: uri
        order:
          type: integer
          maximum: 9223372036854775807
          minimum: 0
          format: int64
      required:
      - id
      - image
    Item:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        seller:
          allOf:
          - $ref: '#/components/schemas/PublicUserInfo'
          readOnly: true
        images:
          type: array
          items:
            $ref: '#/components/schemas/Image'
          readOnly: true
        title:
          type: string
          maxLength: 200
        description:
          type: string
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        stock:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        negotiable:
          type: boolean
        min_negotiable_price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
          nullable: true
        tags:
          type: array
          items:
            type: integer
      required:
      - created_at
      - description
      - id
      - images
      - price
      - seller
      - title
      - updated_at
    ItemBasic:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 200
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        stock:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        negotiable:
          type: boolean
        seller:
          $ref: '#/components/schemas/SellerUser'
        rating:
          type: string
          format: decimal
          pattern: ^-?\d{0,1}(?:\.\d{0,1})?$
          readOnly: true
        thumbnail:
          type: string
          readOnly: true
      required:
      - id
      - price
      - rating
      - seller
      - thumbnail
      - title
    ItemReview:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        rating:
          type: string
          format: decimal
          pattern: ^-?\d{0,1}(?:\.\d{0,1})?$
        comment:
          type: string
          nullable: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        item:
          type: integer
      required:
      - created_at
      - id
      - item
      - rating
    PaginatedItemBasicList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/ItemBasic'
    PatchedItem:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        seller:
          allOf:
          - $ref: '#/components/schemas/PublicUserInfo'
          readOnly: true
        images:
          type: array
          items:
            $ref: '#/components/schemas/Image'
          readOnly: true
        title:
          type: string
          maxLength: 200
        description:
          type: string
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        stock:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        negotiable:
          type: boolean
        min_negotiable_price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
          nullable: true
        tags:
          type: array
          items:
            type: integer
    PublicUserInfo:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        is_verified_seller:
          type: boolean
        avatar:
          type: array
          items:
            $ref: '#/components/schemas/Image'
          readOnly: true
      required:
      - avatar
      - id
      - username
    SellerUser:
      type: object
      properties:
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        is_verified_seller:
          type: boolean
      required:
      - username
    User:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        avatar:
          type: array
          items:
            $ref: '#/components/schemas/Image'
          readOnly: true
        password:
          type: string
          maxLength: 128
        last_login:
          type: string
          format: date-time
          nullable: true
        is_superuser:
          type: boolean
          title: Superuser status
          description: Designates that this user has all permissions without explicitly
            assigning them.
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        first_name:
          type: string
          maxLength: 150
        last_name:
          type: string
          maxLength: 150
        email:
          type: string
          format: email
          title: Email address
          maxLength: 254
        is_staff:
          type: boolean
          title: Staff status
          description: Designates whether the user can log into this admin site.
        is_active:
          type: boolean
          title: Active
          description: Designates whether this user should be treated as active. Unselect
            this instead of deleting accounts.
        date_joined:
          type: string
          format: date-time
        phone:
          type: string
          maxLength: 20
        is_verified_seller:
          type: boolean
        groups:
          type: array
          items:
            type: integer
          description: The groups this user belongs to. A user will get all permissions
            granted to each of their groups.
        user_permissions:
          type: array
          items:
            type: integer
          description: Specific permissions for this user.
      required:
      - avatar
      - id
      - password
      - username
    UserBasic:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        first_name:
          type: string
          maxLength: 150
        last_name:
          type: string
          maxLength: 150
      required:
      - id
      - username
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
