# Generated by Django 5.2.7 on 2026-03-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analytics',
            name='user_count',
        ),
        migrations.AddField(
            model_name='analytics',
            name='admin_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analytics',
            name='distinct_tags_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analytics',
            name='member_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analytics',
            name='member_items_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analytics',
            name='member_used_tags_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analytics',
            name='seller_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analytics',
            name='seller_items_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analytics',
            name='seller_used_tags_count',
            field=models.IntegerField(default=0),
        ),
    ]
