# Generated by Django 5.2.7 on 2026-03-16 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_remove_analytics_user_count_analytics_admin_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analytics',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
