# Generated by Django 5.2.7 on 2026-03-17 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_rename_timestamp_analytics_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Analytics',
            new_name='SiteAnalytics',
        ),
    ]
