# Generated by Django 5.2.7 on 2026-03-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_rename_analytics_siteanalytics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteanalytics',
            old_name='distinct_tags_count',
            new_name='member_distinct_tags_count',
        ),
        migrations.AddField(
            model_name='siteanalytics',
            name='seller_distinct_tags_count',
            field=models.IntegerField(default=0),
        ),
    ]
