# Generated by Django 5.2.7 on 2026-03-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_selleranalytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleranalytics',
            name='accepted_request_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='selleranalytics',
            name='distinct_tags_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='selleranalytics',
            name='items_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='selleranalytics',
            name='rejected_request_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='selleranalytics',
            name='total_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='selleranalytics',
            name='used_tags_count',
            field=models.IntegerField(default=0),
        ),
    ]
