# Generated by Django 5.2.7 on 2025-12-19 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendingrequests', '0004_remove_pendingrequest_is_answered_and_more'),
        ('review', '0004_alter_accountreview_rating_alter_itemreview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountreview',
            name='offer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_reviewed', to='pendingrequests.pendingrequest'),
        ),
        migrations.AlterField(
            model_name='itemreview',
            name='offer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_reviewed', to='pendingrequests.pendingrequest'),
        ),
    ]
