# Generated by Django 5.2.7 on 2025-11-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('is_answered', models.BooleanField(default=False)),
            ],
        ),
    ]
