# Generated by Django 5.2.7 on 2025-11-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendingrequests', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingrequest',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
