# Generated by Django 5.2.7 on 2025-12-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendingrequests', '0003_pendingrequest_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingrequest',
            name='is_answered',
        ),
        migrations.AddField(
            model_name='pendingrequest',
            name='response',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
