# Generated by Django 5.2.7 on 2026-03-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendingrequests', '0004_remove_pendingrequest_is_answered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingrequest',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
