# Generated by Django 5.2.7 on 2026-03-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendingrequests', '0005_pendingrequest_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingrequest',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
