# Generated by Django 5.2.7 on 2026-03-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendingrequests', '0006_pendingrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingrequest',
            name='owner_response_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
