# Generated by Django 5.2.7 on 2026-03-18 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pendingrequests', '0007_pendingrequest_owner_response_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingrequest',
            name='status',
        ),
    ]
