# Generated by Django 5.2.7 on 2025-11-12 17:29

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=user.models.dynamic_image_upload_path),
        ),
    ]
