# Generated by Django 5.2.7 on 2025-11-20 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('youtube', 'YouTube'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('twitter', 'X (Twitter)'), ('snapchat', 'Snapchat'), ('linkedin', 'LinkedIn'), ('pinterest', 'Pinterest')], max_length=30)),
                ('url', models.URLField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'platform')},
            },
        ),
    ]
