# Generated by Django 5.2.7 on 2026-02-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_sociallink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('youtube', 'YouTube'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('twitter', 'X (Twitter)'), ('snapchat', 'Snapchat'), ('linkedin', 'LinkedIn'), ('pinterest', 'Pinterest'), ('email', 'Email')], max_length=30),
        ),
    ]
